# Site settings
name: YXHYW
location: 安徽合肥
company: Unemployed
position: 数据分析师
github: https://github.com/YXHYW
facebook: https://www.facebook.com/
phone: 177xxxxxxxx
email: youxiaheyuwei@outlook.com

baseurl: "/yxhyw.github.io"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

